[build]
  command = "npm run build:netlify"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static pages for 1 hour (they don't change often)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/travel"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/venue"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/schedule"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/registry"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/faq"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache images for 1 year
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
